### ISSUE TITLE
Translation for Portuguese Brazilian

### ISSUE THREAD

**Issue by wanderleihuttel** [Securepoint/openvpn-client#11]
Hello!
My name is Wanderlei and I'm from Brazil.
I would like to help with project. Is it possible to help translating for Brazilian Portuguese ? How could I translate?

Best regards!
Wanderlei Hüttel

**Comment by wanderleihuttel** [comment]
Nobody answer?

**Comment by wanderleihuttel** [comment]
@QtOlli can you answer?

**Comment by Flashtony76** [comment]
Hi @wanderleihuttel,

the installer only supports two languages right now.
Unfortunately there is quite a lot of rework necessary in order to offer additional languages.
We are planning a new release and will keep on mind the possibility to add additional translations.
We do not have a fixed timeline for the release yet.
I will update you once it is done.

Kind regards

Flashtony
